#!/bin/bash
#  This script uses xrandr to change monitor options
LAPTOP=eDP-1
HDMI=DP-1-1
DVI=DP-1-2
VGA=DP-1-3

HAS_HDMI=$(xrandr --listactivemonitors | egrep $HDMI | wc -l )
HAS_DVI=$(xrandr --listactivemonitors | egrep $DVI | wc -l )
HAS_VGA=$(xrandr --listactivemonitors | egrep $VGA | wc -l )
echo $HAS_HDMI $HAS_DVI $HAS_VGA
echo $HDMI $DVI $VGA $LAPTOP
if [ $HAS_HDMI -eq 1 -a $HAS_VGA -eq 1 ]; then
    xrandr --output $VGA --mode 1920x1200
    xrandr --output $HDMI --mode 1920x1200 --primary --left-of $VGA
    xrandr --output $LAPTOP --off
elif [ $HAS_HDMI -eq 1 ]; then
    xrandr --output $HDMI --mode 1920x1200 --primary
    xrandr --output $LAPTOP --off
else
    xrandr --output $LAPTOP --primary --mode 1920x1080
fi
